name: Build and Release uYouEnhanced IPA

on:
  workflow_dispatch:
    inputs:
      yt_version:
        description: 'YouTube Version (Leave blank for default)'
        required: false
        default: '19.08.2'
        type: string

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Setup Theos
        run: |
          echo "GH_EXECUTIVE_SERVER=1" >> $GITHUB_ENV
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Run Build Script
        run: |
          # Build the tweak and package the IPA
          make clean package FINALPACKAGE=1

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uYouEnhanced-IPA
          path: main/packages/*.ipa
